import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import"./index.css";
type Event={text:string;delay:number;kind?:string};
const events:Event[]=[{text:"Ödev yükleniyor...",delay:2200},{text:"Dosyalar kontrol ediliyor...",delay:2200},{text:"İçerik hazırlanıyor...",delay:2200},{text:"Fotosentez modülü başlatılıyor...",delay:2400},{text:"Hazır.",delay:1600},{text:"Bir dakika...",delay:1800},{text:"Gerçekten ödevi açtınız.",delay:2200},{text:"İyi.",delay:1500},{text:"Saat ${clock}.",delay:1900},{text:"Bu arada...",delay:1700},{text:"Buraya kadar gelmeniz gerekiyordu.",delay:2200},{text:"Çünkü birazdan ödev yerine başka bir şey göreceksiniz.",delay:2600},{text:"Ama merak etmeyin.",delay:1700},{text:"Beklemek tamamen sizin seçiminiz.",delay:1900},{text:"Hem de dakikalardır bekliyorsunuz.",delay:2200},{text:"Hâlâ bir şey öğrenemediniz.",delay:2300},{text:"Fotosentez hakkında sıfır bilgi.",delay:2200},{text:"Ama en azından sabrınızı test ediyorum.",delay:2300},{text:"Ve sabrınız gerçekten etkileyici.",delay:2000},{text:"Çünkü hâlâ kapatmadınız.",delay:2200},{text:"Şimdi bilgisayarınızda bazı şeyler oluyor gibi görünecek.",delay:2500,kind:"system"},{text:"Tarayıcı oturumu kontrol ediliyor...",delay:2200,kind:"system"},{text:"Açık sekmeler inceleniyor...",delay:2200,kind:"system"},{text:"Bu sekme bulundu.",delay:2100,kind:"warning"},{text:"Evet, bu sekme.",delay:1800},{text:"Hâlâ buradasınız.",delay:2100},{text:"Boşuna beklediğinizi söylemiştim.",delay:2300},{text:"Ama şimdi kapatırsanız bütün bu bekleyiş gerçekten boşa gidecek.",delay:2700},{text:"O yüzden biraz daha bekleyeceksiniz.",delay:2200},{text:"3",delay:1100,kind:"count"},{text:"2",delay:1100,kind:"count"},{text:"1",delay:1300,kind:"count"},{text:"BAĞLANTI KESİLDİ",delay:2500,kind:"alarm"},{text:"...",delay:1600},{text:"Evet.",delay:1500},{text:"Bunca dakika beklediniz.",delay:2100},{text:"Ve sonunda...",delay:1800},{text:"...ödev falan açılmadı.",delay:2300},{text:"Çünkü ben size gerçek ödevi göstereceğimi hiç söylemedim.",delay:2700},{text:"Önceki ödevi size özellikle göstermiştim.",delay:2300},{text:"Sadece merak edip tekrar geleceğinizi görmek için.",delay:2600},{text:"Ve geldiniz.",delay:1800},{text:"Hem de isteyerek.",delay:1900},{text:"TUZAĞIMA DÜŞTÜNÜZ.",delay:3200,kind:"trap"},{text:"Şimdi son bir şey.",delay:2100},{text:"HANGİNİZ AÇTIYSA",delay:1700,kind:"final"},{text:"BANA MESAJ ATSIN.",delay:2200,kind:"final"},{text:"Gönderen: Hilmi Selim Şen",delay:0,kind:"signature"}];
function sound(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return()=>{};const c=new C(),m=c.createGain();m.gain.value=.045;m.connect(c.destination);const d=c.createOscillator(),g=c.createGain();d.type="sine";d.frequency.value=49;g.gain.value=.18;d.connect(g).connect(m);d.start();let n=0;const t=setInterval(()=>{n++;const o=c.createOscillator(),x=c.createGain();o.type=n%4===0?"triangle":"sine";o.frequency.value=n%4===0?98:62;x.gain.value=.13;x.gain.exponentialRampToValueAtTime(.001,c.currentTime+.5);o.connect(x).connect(m);o.start();o.stop(c.currentTime+.5)},1250);return()=>{clearInterval(t);d.stop();c.close()}};
function App(){const[start,setStart]=useState(false),[idx,setIdx]=useState(0),[shown,setShown]=useState<string[]>([]),[progress,setProgress]=useState(0),[desktop,setDesktop]=useState(false),[glitch,setGlitch]=useState(false),[clock,setClock]=useState("");const stop=useRef<(()=>void)|null>(null);
useEffect(()=>{if(!start||idx>=events.length)return;const e=events[idx];setProgress(0);const tick=setInterval(()=>setProgress(p=>Math.min(100,p+1000/e.delay*100)),100);const timer=setTimeout(()=>{setShown(s=>[...s,e.text]);setIdx(i=>i+1)},e.delay);if(e.kind==="system"||e.kind==="warning")setDesktop(true);if(e.kind==="alarm"||e.kind==="trap"){setGlitch(true);setTimeout(()=>setGlitch(false),450)}return()=>{clearInterval(tick);clearTimeout(timer)}},[start,idx]);
useEffect(()=>{if(!start)return;const u=()=>setClock(new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date()));u();const t=setInterval(u,1000);return()=>clearInterval(t)},[start]);useEffect(()=>{if(start)document.title=idx>15?"DİKKAT":"Fotosentez | İnteraktif Ödev"},[start,idx]);
const begin=async()=>{setStart(true);stop.current=sound();try{await document.documentElement.requestFullscreen?.()}catch{}};
if(!start)return <main className="intro"><div className="sheet"><div className="tag">BİYOLOJİ • İNTERAKTİF ÖDEV</div><h1>Fotosentez</h1><p>Fotosentezin gerçekleşme sürecini incelemek için aşağıdaki bölümü açın.</p><button onClick={begin}>Ödevi Aç</button><span>İnteraktif içerik yükleniyor...</span></div></main>;
const current=events[Math.max(0,idx-1)];
const renderedShown=shown.map(x=>x==="Saat ${clock}."?"Saat "+clock+".":x);
return <main className={`scene ${current?.kind||""} ${desktop?"desktopMode":""} ${glitch?"glitch":""}`}>{desktop&&<div className="fakeDesktop"><div className="fakeWindow"><div className="titlebar">Görev Yöneticisi <b>— □ ×</b></div><div className="inside"><strong>Arka plan işlemleri</strong><div>Ödev doğrulama <em>%{Math.min(100,Math.floor(idx/events.length*100))}</em></div><div>Tarayıcı oturumu <em>aktif</em></div><div>Güvenlik denetimi <em>inceleniyor</em></div></div></div><div className="barBottom">⊞　 Ödev　　Tarayıcı　　Görev Yöneticisi　　{clock}</div></div>}<div className="noise"/><section className="story"><div className="tiny">PHOTOSYNTHESIS.EXE　•　SESSION ACTIVE</div>{renderedShown.slice(-5).map((x,i)=><p key={shown.length-5+i} className={i===4?"latest":""}>{x}</p>)}{idx<events.length&&<div className="loading"><i style={{width:progress+"%"}}/></div>}{idx>=events.length&&<div className="finalImage"><img src="/trol.png" alt=""/></div>}</section></main>}
createRoot(document.getElementById("root")!).render(<App/>);